### ISSUE TITLE
Review timezone settings

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#902] opened 2019-05-30 12:03 UTC
When starting a discussion, it always shows the time as "2 hours ago". Probably, we aren't using the timezone correctly (note that we are UTC +2).

**Comment by inyono** [comment] 2019-05-30 12:05
@Knorrke: "Seems like we save times as UTC but interpret them as UTC + 2". Things to look at: `timeAgo` view helper and datetime fields in forms.

**Comment by Knorrke** [comment] 2019-05-30 12:52
actually, duplicate of #457^^

**Comment by inyono** [comment] 2019-05-30 20:44
“3 years ago” wtf

**Comment by Knorrke** [comment] 2019-05-30 21:02
No no that must be a wrong timestamp :sweat_smile:

**Closed** 2019-06-03 17:09 UTC
