### ISSUE TITLE
Stay within curriculum taxonomy

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#893] opened 2019-05-09 13:17 UTC
If user comes from curriculum taxonomy they should stay in curriculum taxonomy.

Open questions
- how to handle links to content within the same curriculum?

**Comment by Knorrke** [comment] 2019-05-20 07:59
Duplicate of #531

**Closed** 2019-05-20 08:00 UTC

**Comment by simonkoehl** [comment] 2019-05-20 09:21
Danke für den Hinweis @Knorrke ! Habe #531 stattdessen dem Product Managemet Board hinzugefügt
